### PR TITLE
Added template files

### PR DESCRIPTION
**Pull request by rajmahendra**

### CODE REVIEW

**Comment by jonbullock** [comment]
Hi Raj 

These templates will change soon, can you avoid having a local copy some how?

Jon

**Comment by rajmahendra** [comment]
Yes. i do have idea of creating dedicated to the plugin.  Thank you for reminding :)   We will change it.  @manimanasamylavarapu

**Comment by rajmahendra** [comment]
@jonbullock  Is it ok to have the example zip template ?  the individual content files header meta will be changes later with places holders to automatically add page/post related info.

**Comment by jonbullock** [comment]
Not sure I follow, do you want to use the example template zip file?

**Comment by manimanasamylavarapu** [comment]
@jonbullock 
Currently the way we are doing jbake project set up is
1) Have template zip files(just like example_project_freemarker in installed jbake) in resources folder of forge-jbake-addon
2)Copy the respective templateType.zip(freemarker/Groovy/ThymeLeaf) to user's maven project folder(src/main/jbake location ).Ofcourse Unzipping is being taken care of.And this happens when a user tries to set up jbake initial project structure.Just like when we run "jbake -i" from command line.

So this is what we have done in case of jbake-setup command.Raj is asking if this approach is fine or not,i mean having template.zips in resource folder.
I have gone through Jbake core code , and i have noticed that  when user gives "jbake -i" ,even there it copies example_project_freemarker /groovy/thym zip code to user created jbake project folder.I noticed this in org.jbake.launcher.Init.java run method.So we tried following similar approach without having jbake's dependency on forge-jbake-addon.

 Please let us know how the templates are going to change.And also if our current approach is not very efficient we can discuss and change accordingly.

Thank you!

**Comment by jonbullock** [comment]
Having a copy of them in the Forge plugin as a ZIP file is absolutely fine, follows the approach in JBake core and still allows the end user to customise them.

Have a look at the jbake-core Maven pom as it constructs the template ZIP files on the fly by downloading a copy from GitHub when the project is built to make sure the latest version is used. Would be good if the Forge plugin did the same.

**Pull request merged**
